### ISSUE TITLE
Experience Event: should commerce be transaction?

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#100]
Should we rename the commerce property to transaction?

**Comment by cmathis** [comment]
"commerce" is what has been used by data producers for a few months now.  Not sure we can handle a change at this time.

**Comment by trieloff** [comment]
I get that a change would be inconvenient, but my question is a about the scope of the property: are we planning to restrict this only to commerce (buying goods) or all kinds of transactions (managing subscriptions, memberships, etc.)

If it's the former, we should stay with `commerce`. If it's the latter, we need to decide if it makes sense to have either both a `commerce` and a `transaction` property, and where the line between the two would be, or to expand the scope and name of the `commerce` property accordingly.

For data producers that are posting data according to a pre-1.0 version of XDM, you might want to consider adapters to re-write the data, but until we've reached 1.0, there can and will be changes. (Unless we agree to change the rules)

**Comment by cdegroot-adobe** [comment]
```transaction``` is a subset of ```commerce```, the intent of this area is more then a "transaction" so I am much more comfortable with ```commerce```.

**Comment by trieloff** [comment]
Ok.
