### ISSUE TITLE
Rollback metrics related schemas to platform's original definition.

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#107]
## What are the schemas that are affected by the issue
All metrics related schemas in data folder

## What are examples of products that are impacted by the issue
platform xed conversion

**Comment by trieloff** [comment]
How does this relate to and address the issues raised in #84 ?

**Comment by jwen-adobe** [comment]
@cluby @kstreete @cmathis
The original definition was proposed by analytics and reviewed internally at platform. Basically, it needs to satisfy the requirements below. With all the latest changes, the impact needs to be re-evaluated from analytics point of view. Besides, 1). the structure change creates schema for each metric, so if analytics has eVar1 to eVar1000, are we going to create 1000 schemas? 2). We want core metrics not using URI but shorter fields grouped by different categories.

Analytics requirements:
=================
-Explicit fields for each metric that the user can directly populate or query.  No arrays.
-Structure that lets us group related metrics by “vertical” like page-views and link-clicks under web, sends under direct-marketing, etc
-For the above structure I would like it to be similar to the way we structure the additional data/dimensions in ExperienceEvent so we are consistent and intuitive
-The ability to set a float/double value for the metric
-An optional unique identifier for the metric/event to support deduplication of the metric/event downstream while still keeping the rest of the ExperienceEvent
-Ability to have core, Adobe solution specific, partners, and customer extensions using the same Metric data type for any metric type field
