### ISSUE TITLE
Add new schemas from platform

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#109]
## What are the schemas that are affected by the issue
n/a, only add new schemas

## What are examples of products that are impacted by the issue
platform xdm tooling

**Comment by trieloff** [comment]
Can you give a bit more background? What are the schemas that you want to add?

**Comment by jwen-adobe** [comment]
These are newly added schemas from platform PMs since last merge. We need to sync them into the central repo. @cdegroot-adobe 

-identity
-namespace
-times
-openinghours
-segment
-store
-propensity

**Comment by jwen-adobe** [comment]
Close for now as this is duplicate.
