### ISSUE TITLE
Rollback schema.org geo* schemas back to original definition

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#111]
## What are the schemas that are affected by the issue
schema.org geo* related schemas

## What are examples of products that are impacted by the issue
platform xdm tooling

**Comment by trieloff** [comment]
What's the reason for this rollback? Is there a problem with the validity of the schema.org definition?

**Comment by jwen-adobe** [comment]
1. We can not resolve and validate "$ref": "https:/schema.org/geoShape" etc. as these are web pages.
2. We do not need all the fields from schema.org definition and we can use our mini version stored locally.

**Comment by jwen-adobe** [comment]
Close this and will use local repo file for validation/deref
