### ISSUE TITLE
Update schema enduserids

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#113]
## What are the schemas that are affected by the issue
enduserids
identity
namespace

## What are examples of products that are impacted by the issue
platform xdm tooling

**Comment by trieloff** [comment]
Can you clarify how the schema should be updated?

**Comment by jwen-adobe** [comment]
See PR here: https://github.com/adobe/xdm/pull/114

1. introduce two new schemas identity and namespace
2. remove the patternProperties and call out the fields explicitly like below:

"properties": {
        "https://ns.adobe.com/experience/mcId": {
          "title": "Adobe Marketing Cloud Id",
          "$ref": "https://ns.adobe.com/xdm/context/identity",
          "description": "A unique identifier from Adobe Marketing Cloud."
        },
        "https://ns.adobe.com/experience/analytics": {
          "title": "Adobe Analytics Cloud End User Ids",
          "$ref": "https://ns.adobe.com/xdm/context/identity",
          "description": "Adobe Analytics Cloud extension to End User Ids."
        }
      }

**Comment by jwen-adobe** [comment]
This is fixed.
