### ISSUE TITLE
node lint error

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#115]
Got errors when running the "node lint", the error is:
"Schema xxxxx.schema.json does not validate against meta.schema.json
/bin/sh: ajv: command not found" 

I followed install instructions like "npm install", "npm run package" etc. This worked before..

OS: macOS High Sierra version 10.13.3 (17D47)
Node: version

**Comment by trieloff** [comment]
Can you try with a fresh checkout of `master` and post the output of following commands:

* `node --version`
* `npm --version`
* `npm installl`
* `npm run lint`

I'd like to make sure we can reproduce this on the CI system, too.

**Comment by trieloff** [comment]
Can you re-try this from `master`? I think #97 and #102 should have fixed this. Please re-open if the issue persists.

**Comment by trieloff** [comment]
Thanks, I can reproduce it now. It fails with `bash`, but works with `zsh`.

**Comment by jwen-adobe** [comment]
fixed.
