### ISSUE TITLE
Change timestamp of experienceevent to integer

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#117]
## What are the schemas that are affected by the issue
experienceevent

## What are examples of products that are impacted by the issue
platform xdm definition

**Comment by trieloff** [comment]
Why would we use integers for timestamps in one place only, and the JSON Schema built-in data types in all other places?

I think we need to have a good justification for 

1. this kind of internal inconsistency
2. this deviation from the JSON Schema standard

**Comment by kstreeter** [comment]
@trieloff I suggest we close this, we should use the built-in type.

**Comment by kstreeter** [comment]
Actually, I see the associated PR is already closed, so I am going to close this issue now.
