### ISSUE TITLE
Is Asset Rating user editable?

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#13]
Right now, it is marked as not user editable, but that conflicts with the description that says the asset rating has been set by a user.

**Comment by lrosenthol** [comment]
Yes, it should be.  I'll try to submit a PR for the change

**Comment by trieloff** [comment]
Cool. The semantics of being user editable are a bit hazy anyway, so clarifying this somewhere in `docs` would also be beneficial.

**Comment by trieloff** [comment]
https://github.com/adobe/xdm/blob/master/schemas/assets/asset.schema.json#L285 if you are looking for a quick fix.

**Comment by kgera** [comment]
submitted PR: https://github.com/adobe/xdm/pull/54 for review.
