### ISSUE TITLE
Activity Steams Schemas are Messy

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#14]
- missing titles
- missing descriptions
- circular references (making @ankaur's life difficult)

@majindal can you help improving this?

**Comment by trieloff** [comment]
@theManikJindal once you've done this, I'm happy to take a PR that rejects PRs without examples

**Comment by theManikJindal** [comment]
@trieloff I am just on the verge of raising a PR that fixes this issue. However, there are some places where the tooling is failing. 

For example, if one defines a schema having an array at the root, the tooling throws an error. Tooling wants only `objects` to be at the root level. 

Example schema: 
```
{
    "type": "array",
}
```

Example instance:
```
["fails", "to", "validate", "this"]
```

**Comment by trieloff** [comment]
Change the meta schema to allow arrays.
