### ISSUE TITLE
experienceevent @type

### ISSUE THREAD

**Issue by cmathis** [adobe/xdm#144]
@cdegroot-adobe, @kstreeter 

Anyone apposed to us adding a @type to experienceevent? This would be a simple URI formatted value that can be used to assign a high level type to the event. Campaign would use this for filtering purposes without having to inspect the actual metrics or other meta-data that may be included.

**Comment by trieloff** [comment]
I think it is a good idea, but please make sure that it is aligned with the `EventEnvelope`, which already has a `@type`: https://github.com/adobe/xdm/blob/master/docs/reference/common/eventenvelope.schema.md

**Comment by cdegroot-adobe** [comment]
@cmathis I think that ```@type is problematic to add to the top level of ExperienceEvent. By definition an ExperienceEvent is supposed to be an oblique observation of the circumstances around a set of metrics that occurred at the same instance for a given endUser. Adding hints is likely giving the specific impression in how to interpret it. 

We do tend as people to talk about events as having a primary type "Purchase, send etc". So that gives me pause is saying no to this, but I am leaning against it.

Are we going to require that creators of ExperienceEvents make a determination of the primary event and then set it, if so then this makes more sense, but adds to the load they have to ETL in. The problem I have is that if it is not set then the consumer still needs to interpret the metrics in their context. 

It is really also not always possible to set it. For example in web there is no formal event raised for a CartAbandon. It is really a query of sessions where products were added to the cart without a purchase, and then a period of inactivity in the session.

**Comment by cmathis** [comment]
Would be good to back to campaign and understand better why they requested it. I never envisioned it as a required field that every ExperienceEvent would have. It's an optional field that producer and consumer can agree on. In the case of Campaign, that producer is the customers mobile app and the consumer being the Campaign Voyager system thats listening for these messages over Pipeline. 

I do wonder if what they want to do is better suited with the EventEnvelope which has a @type and caters more to these custom payloads (aka messages) that they want to define and consume.

**Comment by cdegroot-adobe** [comment]
This has been resolved by the Campaign team using a campaign specific field in their extension.

Closing issue.
