### ISSUE TITLE
Provide a way to mark schemas as stable/stabilizing/experimental

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#161]
- [x] Introduce a new property `meta:status` with an `enum` of property values.
- [x] Update `Contributing` with rules what qualifies as `stable` (no open issues, has been in `stabilizing` for 1 month without major changes)

## What are the schemas that are affected by the issue

- all schemas

## What are examples of products that are impacted by the issue

- data platform

**Comment by kstreeter** [comment]
Hi @trieloff, I'd like to suggest we also include a "deprecated" state, which can be applied to stable schemas when they are superceded by another model or set of models.

**Comment by trieloff** [comment]
Good idea, that #165 already implemented.

**Comment by trieloff** [comment]
@kstreeter should we have a `superseded-by` relationship in #155 in addition to the `deprecated` flag?
