### ISSUE TITLE
Adobe Target Extension is using xdm:page in non-compliant way

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#175]
As discussed in https://github.com/adobe/xdm/commit/6f8fd223bab81828784049ea211c43a9617b47fb – the Adobe Target extension is using the property `xdm:page` when it should not (too easily confused with pages in documents).

@lrosenthol suggested using a separate namespace, and while I agree that `xdm` isthe wrong namespace, I don’t think we should have one namespace for each product, so something like `adobe-ext` would work better for me.

**Comment by lrosenthol** [comment]
thanks!

The problem with putting all Adobe extensions into a single namespace would be versioning and contention between products.   Why can't each product have a separate namespace?  Or better would be to use the concept and not the product...

**Comment by trieloff** [comment]
https://github.com/adobe/xdm/commit/6f8fd223bab81828784049ea211c43a9617b47fb#diff-07d5b12fb4e710ea4bb3d7a671444828 - it looks like it’s not in master anymore.

**Comment by cmathis** [comment]
The only place I'm seeing a xdm:page is in the open PR here - https://github.com/adobe/xdm/pull/143

That's fine if we want to avoid using that term. Like I mentioned on slack it would be nice to know of all these rules and the reason why so we can avoid making those in future PR's.

**Comment by jwen-adobe** [comment]
@trieloff  no more issues here right?

**Comment by trieloff** [comment]
Nope.
