### ISSUE TITLE
Auditable createdOn and modi

### ISSUE THREAD

**Issue by cmathis** [adobe/xdm#176]
@trieloff and @kstreeter 

The original **auditlog** schema that was in a previous PR that came with the profile schema appears it was converted into or replaced with the new [auditable](https://github.com/adobe/xdm/blob/master/schemas/common/auditable.schema.json). As part of this we lost two fields named "createdOn" and "modifiedOn" that stored the date which the record was created or updated. We need to know if this was removed on purpose or just lost in shuffle and should be added again? If removed on purpose can you explain why?

Thanks

**Comment by trieloff** [comment]
@cmathis have a look at the generated docs:

https://github.com/adobe/xdm/blob/master/docs/reference/common/auditable.schema.md

There is `repo:createdDate` and `repo:lastModifiedDate`, which make them compatible with the equivalent fields in the Adobe Cloud Platform API.

**Comment by cdegroot-adobe** [comment]
@cmathis - can we close this now please?

**Comment by trieloff** [comment]
Closing. Reopen if questions persist.
