### ISSUE TITLE
Move IMSOrg and IMSUser URLs to XDM extensions

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#189]
@asteed's namespace sweep (#179) has produced a couple of interesting findings:

```
http://ns.adobe.com/xdm/IMSOrg
http://ns.adobe.com/xdm/IMSUser
```

These should probably be:
1. XDM extensions
2. Lowercase
3. HTTPs

@theManikJindal – WDYT?

**Comment by trieloff** [comment]
In the same set of files, we have also these URLs:

```
http://ns.adobe.com/xdm/aem/instance
http://ns.adobe.com/xdm/aem/user
http://ns.adobe.com/xdm/asset
http://ns.adobe.com/xdm/assets/asset
http://ns.adobe.com/xdm/assets/asset#
http://ns.adobe.com/xdm/event/created
http://ns.adobe.com/xdm/event/published
http://ns.adobe.com/xdm/event/unpublished
http://ns.adobe.com/xdm/event/updated
http://ns.adobe.com/xdm/page
http://ns.adobe.com/xdm/services
```

**Comment by theManikJindal** [comment]
https://github.com/theManikJindal/xdm/commit/01534666a2811159d07fd4908f264c0b5d2f665f

**Comment by trieloff** [comment]
@theManikJindal will this become a PR?

**Comment by theManikJindal** [comment]
@trieloff the commit was a sample commit for @asteed to look at. It has already become a PR here - https://github.com/adobe/xdm/pull/201
