### ISSUE TITLE
Modify Media Analytics XDM schema to enable ADC migration

### ISSUE THREAD

**Issue by RaduBPavel** [adobe/xdm#1907]
## What are the schemas that are affected by the issue
- `advertisingpoddetails.schema.json`
- `chapterdetails.schema.json`
- `sessiondetails.schema.json`

## What are examples of products that are impacted by the issue
- Adobe Media Analytics

Internal JIRA issue: https://jira.corp.adobe.com/browse/VA-6928

High level changes:
- remove the required property from some fields found in the Advertising Pod Details and Chapter Details schemas
- add a new field in the Session Details schema:`genreList`

**Comment by andrei2102** [comment]
The genreList field addition is an attempt to fix a schema issue without deprecating the media schema and creating a new stable version. The genre already in the schema is a comma separated list and xdm users can't use the gendre values to create breakdowns in CJA.
