### ISSUE TITLE
Better home for "self-service"

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#192]
@asteed's namespace sweep (#179) has produced a couple of interesting findings:

```
https://ns.adobe.com/xdm/selfservice
```

This should not go into XDM root, but find a more appropriate URL.

**Comment by asteed** [comment]
@ktukker-adobe kstreeter any suggestions on _where_ this type of schema should reside or be renamed to?

In `schemas/common/selfservice.schema.json`:
>A Customer Managed Environment is an environment that allows a system integration or deployer to manage applications. This is also known as selfservice.

**Comment by kstreeter** [comment]
@asteed, I feel like we have several schemas that are really descriptions of have Adobe Cloud Platform, as a system, is defined.  This may be better to move to an extension for ACP, but if we do believe this is could be used to describe a general framework for cloud systems we might want to have a "cloud" folder.  

I don't think I would make that change for just this schema though.  It's already in common, and the description makes it clear it is WIP.  I would just mark it experimental and make the namespace match where it resides (common).  We can figure out how to organize it later as it progresses.
