### ISSUE TITLE
Adobe Extension URLs are messy, messy, messy

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#193]
@asteed's namespace sweep (#179) has produced a couple of interesting findings:

```
https://ns.adobe.com/xdm-extensions/adobe/experience/analytics/analytics-extensions
https://ns.adobe.com/xdm-extensions/adobe/experience/target/experienceevent
```

and 

```
https://ns.adobe.com/xdm-extensions/aem/user
https://ns.adobe.com/xdm-extensions/ims/organization
https://ns.adobe.com/xdm-extensions/ims/organization#
https://ns.adobe.com/xdm-extensions/ims/organization#id
https://ns.adobe.com/xdm-extensions/ims/user
https://ns.adobe.com/xdm-extensions/ims/user#
https://ns.adobe.com/xdm-extensions/ims/user#id
```

and 

```
https://ns.adobe.com/experience/analytics
https://ns.adobe.com/experience/analytics/customdimensions/props/prop8
https://ns.adobe.com/experience/analytics/customdimensions/props/prop9
https://ns.adobe.com/experience/analytics/enduser/firsttimestamp
https://ns.adobe.com/experience/analytics/enduser/firstweb
https://ns.adobe.com/experience/analytics/event101to200/event101
https://ns.adobe.com/experience/analytics/event101to200/event102
```

and 

```
https://ns.adobe.com/experience/campaign
https://ns.adobe.com/experience/mcid
https://ns.adobe.com/experience/target
https://ns.adobe.com/experience/target/clientcode
https://ns.adobe.com/experience/target/mboxname
https://ns.adobe.com/experience/target/mboxversion
https://ns.adobe.com/experience/target/pagedetail/pageid
https://ns.adobe.com/experience/target/pagedetail/pagescore
https://ns.adobe.com/experience/target/sessionid
https://ns.adobe.com/experience/tntid
https://ns.adobe.com/experiencecloud/analytics
https://ns.adobe.com/experiencecloud/mcid
```

**Comment by kstreeter** [comment]
My preference is definitely that we skip the "extensions" portion, as it is a bit redundant.  I think the overall pattern of https://ns.adobe.com/{cloud}/{product-or-area} is the way to go.

**Comment by jwen-adobe** [comment]
I think the URLs with "xdm-extensions" in them are $id of schemas while the others are field names with URIs. Currently, the $id is in-sync with the folder structure where the schema resides.

**Comment by cdegroot-adobe** [comment]
@trieloff 
1/
I think we were recommended to use `https://ns.adobe.com/xdm-extensions/adobe/`. Do you have a different recommendation?
If that is still the recommendation then we need to update `https://ns.adobe.com/xdm-extensions/aem/` and `https://ns.adobe.com/xdm-extensions/aem/` as we need to allow extensions from non Adobe entities and these do not cater for this elegantly.

2/
Where are the `https://ns.adobe.com/experiencecloud/*` usages? I cannot find them?

3/
Do you agree with Joe that we have two patterns
`https://ns.adobe.com/xdm-extensions/adobe/*` and
`https://ns.adobe.com/experience/`
Depending on `@id` or field naming? If not please explain the "messy, messy, messy' part you are seeing in a bit more detail.

**Comment by asteed** [comment]
@kstreeter, any input based on @cdegroot-adobe's feedback?

**Comment by kstreeter** [comment]
@asteed , @cdegroot-adobe as I mentioned in my previous comment I don't feel like we should have "extensions" in our namespaces.  It is redundant; everything that is not in one of the prefixed namespaces defined by an XDM is an extension.  We should just give our namespaces some reasonable organization.  <cloud>/<product-or-area> seems like a reasonable one.  

Note I don't think we need to include the term "cloud" in the <cloud> portion, as that is also redundant.    So we should just have things like "experience/analytics" and "experience/aem".  For something like IMS, that crosses clouds and is part of the ACP foundation we should perhaps just have a "acp/ims" or similar.
