### ISSUE TITLE
What about xdm/base URLs

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#194]
Found in @asteed's #179 

```
https://ns.adobe.com/xdm/base/effectiveprivileges
https://ns.adobe.com/xdm/base/extensible.schema.json
https://ns.adobe.com/xdm/base/imsuser#
```

**Comment by asteed** [comment]
1) `https://ns.adobe.com/xdm/base/effectiveprivileges` is referenced in `schemas/external/repo/effectiveprivileges.schema.json` however shouldn't this schema be located in `schemas/common` to match other `xdm/<schema>` items? 
**Suggested Change:** Move the schema to a suitable location and update the namespace to `https://ns.adobe.com/xdm/effectiveprivileges`

2) Looking at `https://ns.adobe.com/xdm/base/extensible.schema.json` in `schemas/common/extensible.description.md`, the schema is now located within the following repo path `schemas/common/extensible.schema.json`
**Suggested Change:** Strip `.schema.json` from the listed namespace and update this value to match the repo location, `https://ns.adobe.com/xdm/extensible`

3) The reference to `xdm/base/imsuser` is another potential duplicate of `xdm/IMSUser` which is visible in `schemas/common/eventenvelope.example.N.json`.
**Suggested Change:** This is currently being discussed in #189 and should follow that resolution

@trieloff @kstreeter, thoughts?

**Comment by kstreeter** [comment]
Hey @asteed, agreed on points 2, 3.  For 1, EffectivePriviledges is a part of the content repository definitions that is contained in the "repo" folder.  That whole thing should probably be moved into extensions, and given a namespace that is compatible with any schema we elect in [Issue 193](https://github.com/adobe/xdm/issues/193)

**Comment by asteed** [comment]
@kstreeter Does the _content respository_ you mention have anything to do with the current `xdm/content/repository` namespace? How does the "repo" folder relate to this existing namespace which is not in an extension namespace. My net goal is to understand where `EffectivePriviledges` would potentially exist (in which 'cloud' as an extension, as you mentioned). 

Once I have a better understanding I'd like to take this particular example (and some of those mentioned in #193) and come up with what these changes would look like.

**Comment by trieloff** [comment]
We use the `repo` namespace for things that are coming out of the Adobe Cloud Platform API, but that are not strictly part of the XDM domain model as they are technical, not experiential. I would also move it into `/schemas/external/repo`

**Comment by asteed** [comment]
Thanks @trieloff! Just to clarify, you're suggesting the following change for `EffectivePrivileges`?
 - Namespace: `ns.adobe.com/xdm/external/repo/effectiveprivileges`

If that's correct, I wanted to bring up the remainder of what is within `schemas/external/repo`. I see that some of the schemas in `schemas/external/repo` are using the namespace `ns.adobe.com/adobecloud/core/1.0/..`, for example:
```
./asset.schema.json:  "$id": "http://ns.adobe.com/adobecloud/core/1.0/asset",
./common.schema.json:  "$id": "http://ns.adobe.com/adobecloud/core/1.0",
./directory.schema.json:  "$id": "http://ns.adobe.com/adobecloud/core/1.0/directory",
./sub-directory.schema.json:  "$id": "http://ns.adobe.com/adobecloud/core/1.0/sub-directory",
```
Should these above schemas be updated as well to `xdm/external/repo/...` ?

**Comment by trieloff** [comment]
No, these are from ACP API, and defined separately.
