### ISSUE TITLE
Clarify state_province in geo.json

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#20]
## What are the schemas that are affected by the issue

`common/geo.schema.json`

## What are examples of products that are impacted by the issue

All products that read geo-information.

## What is the issue

The current name and description are a bit unclear. `state` and `province` describe the US/Canadian perspective, and I can derive that in Germany it would probably be the "Länder" administrative unit. 

What is unclear:
- what's the format? Is it https://en.wikipedia.org/wiki/ISO_3166-2?
- what level of the division? https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country
- should we call it `admin_unit` or `admin_division` instead?

**Comment by trieloff** [comment]
@kstreeter can you provide feedback?

**Comment by trieloff** [comment]
Do we have a dependency on CDM here?

**Comment by kstreeter** [comment]
Yes we do Lars.  I am holding off improving many of these core/common models until we get input from the CDM folks.

**Comment by trieloff** [comment]
All of the questions raised in my original issue have been resolved. I don't consider #266 a fix.
