### ISSUE TITLE
Naming Inconsistency?

### ISSUE THREAD

**Issue by cmathis** [adobe/xdm#208]
Wondering if you can help me understand when a schema is in a "common" namespace and some are in  "context". For example, why is Address have an $id that includes xdm/**common**/, but PhoneNumber has an $id that includes xdm/**context**/?

Same for EmailAddress, what makes it xdm/context and not xdm/common. What is the deciding factor?

**Comment by trieloff** [comment]
Context is for things that describe the consumer of an experience and the data footprint of the consumption or interaction itself. The two anchor-schemas are ExperienceEvent and Profile. 

Schemas should stay within `context` if they are only used within schemas that belong into `context`, but moved into `common` if they are used by schemas in multiple buckets.

Based on this guideline, it might still make sense to move PhoneNumber.

**Comment by cdegroot-adobe** [comment]
@cmathis - shall we move phone number? It is the only one I can see that has this issue.

**Comment by trieloff** [comment]
If you decide to move it, open a separate issue or a PR right away. I consider this question answered.
