### ISSUE TITLE
Remove stateProvinceISO from examples

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#220]
We still have a number of examples that use the `stateProvinceISO` property, which has been replaced by `stateProvince`

**Comment by asteed** [comment]
@trieloff - looking through the examples, each has both `xdm:stateProvince` and `xdm:stateProvinceISO` defined. Do we just expect to _**remove**_ the latter entry from each example?

```
    "xdm:stateProvince": "California",
    "xdm:stateProvinceISO": "CA",
```
