### ISSUE TITLE
Bump version to 0.9

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#246]
Needs package.json and readme updates.

**Comment by asteed** [comment]
I don't see any current release-related information to update within `README.md`. @trieloff, could you explain a bit of how you expect the release should be represented here?

**Comment by trieloff** [comment]
https://github.com/adobe/xdm/blob/master/docs/introduction.md is the biggest piece. 

For Readme.md, I'd add a small section:

# Current Version

XDM is at version … you can find more about our versioning in docs/…
