### ISSUE TITLE
Consider different types of ExperienceEvent

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#249]
I suggest we add `@type` attribute to ExperienceEvent, so that it becomes easier to distinguish the specific interaction and channel that has happened. 

Right now, consumers will have to do elaborate presence checks like this:

```javascript
if (event.web) {
  //it's a web event
  if (event.web.webPageView) {
    //it's a page view
  } else if (event.web.webInteraction) { 
    //it's an on-page interaction
  } else {
    //it's something else
  }
}
```

With a dedicated `@type` attribute and a number of sub-types for `ExperienceEvent` queries and analysis can be greatly simplified and the presence of the appropriate fields can be added as required.

This won't break compatibility with 0.9

**Comment by cdegroot-adobe** [comment]
@trieloff  - lets use the feedback from the customers and internal implementation teams to define this. I think it is a good question.

**Comment by trieloff** [comment]
I spoke with @theManikJindal this morning and it looks like the best way forward is not to add a `@type` to `ExperienceEvent` because it would duplicate the `@type` that exists in `EventEnvelope`. If filtering based on type becomes necessary, do this using the `EventEnvelope` infrastructure.
