### ISSUE TITLE
Rename Metric schema to MetricDefinition + clean up *all* metricDefinitions

### ISSUE THREAD

**Issue by cdegroot-adobe** [adobe/xdm#251]
## What are the schemas that are affected by the issue
https://github.com/adobe/xdm/blob/master/schemas/data/metric.schema.json

## What are examples of products that are impacted by the issue
Analytics, Campaign, Target

The structure of metrics in ExperienceEvent is confusing
There is a `xdm:metrics` dictionary that contains entries of type `https://github.com/adobe/xdm/blob/master/schemas/data/measure.schema.json` but `measures` are defined as `metrics`.

This bug fixes two things:
1. Clarifies that a metric is really a 'metric definition'. 
1. Add and update all instances of the new 'metric definitions' as some are missing and all are currently incomplete.

**Comment by kstreeter** [comment]
@trieloff , @cdegroot-adobe can this be closed now that #254 has been merged?

**Comment by trieloff** [comment]
#254 is the first part of this issue.

@cdegroot-adobe still needs to review the descriptions of the metric definitions.
