### ISSUE TITLE
modelling self service

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#27]
## What are the schemas that are affected by the issue

None - new schema

## What are examples of products that are impacted by the issue

Ethos, marketing.adobe.com provisioning and deployment in general, self service.

I have been asked to try and represent the terminology in https://wiki.corp.adobe.com/display/~asaar/Self+Service+-+Terminology+and+Data+Model in XDM in a way that works for all of Adobe, not specific to AEM and probably not specific to deployment on Ethos. (ie including self service environments outside the Adobe Platform).

**Comment by trieloff** [comment]
@ieb should this issue stay open, i.e. are there more schemas to be expected?

**Comment by ieb** [comment]
There probably will be more detail that needs to be added as the schema is used, but I think those can be dealt with in follow up issues or pull requests. Please feel free to resolve this issue.
