### ISSUE TITLE
Improve consistency and provide guidelines for use of nested JSON structure versus namespaces

### ISSUE THREAD

**Issue by kstreeter** [adobe/xdm#277]
I think we need to develop more consistent guidance on when it is appropriate to create new namespaces, and when nested JSON structures should be used instead.  We use both ways to organize things in different schemas, and many schemas mix both methods at the same time.

While this could be considered a matter of style, as we have continued to use these schemas in the data platform we have found that the practice of mixing methods creates significant usability issues.  For example, UI tools that create or consume XDM (like data pickers) are generally implemented as tree widgets.  What does the widget show?  Does it show the the JSON nested structure?  Does it show the namespace structure?  Both...sometimes or always?

I feel we need to be much more prescriptive about namespaces.  We had previously agreed to limit the number of prefixed namespaces, saying only major areas should have a prefix and those areas should then be consistent internally.  But in many places (channels, metrics, Analytics and Campaign extensions) we have introduced many namespaces in full URIs.  So I don't think we are really following the policy of "namespace moderation" we had discussed early on.

I have a proposal for clear guidelines on when to use namespaces versus when to use structure:

  * Namespaces are *not* used to organize data.  They are used to prevent name conflicts.
  * Name conflicts occur across organization and domain boundaries.  We should have namespaces to keep different organizations or groups working in parallel.
  * Within an organization or domain, there should only be *one* namespace.  JSON structure or more explicit naming of fields should be used to differentiate names.

If we adopt this, our tools will in most cases be able to drop the namespaces completely.  Conflicts will happen of course, but they will be rare cases that can handled in the tools in ways that may be less user-friendly (for example, showing the URI in a detail box or popup).

To implement this, we need to:

 * Revisit the namespaces used in channels, metrics, and the extensions.
 * Add a section on these guidelines to contributing.  

## What are the schemas that are affected by the issue

All, but this issue is particularly apparent on the definitions of channels, of the definitions of metrics, and in the Analytics and Campaign extensions.

## What are examples of products that are impacted by the issue

Campaign, Analytics

**Comment by trieloff** [comment]
I think it would help to point out a couple of schemas where this is a problem today. 

In some of the places you've mentioned, we are using URIs not as namespaces per se, but for entity identification. 

In cases where we have many entities, it seems to be a simpler and more consistent way to use URIs everywhere instead of having a mix where some areas use URIs and others use simple names.

- metrics: we can assume that every customer will have a couple of own metrics and every vendor will bring addition metrics, resulting in potentially tens of thousands of metric definitions.
- channels: I expect more than a 100 different channels, most of them vendor-defined

**Comment by kstreeter** [comment]
Yes, happy to give some specific examples:

**Campaign extensions**

The campaign extensions have properties like "https://ns.adobe.com/experience/campaign/delivery/id" "https://ns.adobe.com/experience/campaign/campaign/id".  If "delivery" and "campaign" are important organizing concepts, they should be nested structures not in a new namespace.  Campaign should have one namepace, ""https://ns.adobe.com/experience/campaign".

The above is particularly problematic.  What will this look like in a tree widget?  They will both be "id", and the user will have to click in them to tell one from the other.

**Analytics Extensions**

The Analytics extensions have properties like "https://ns.adobe.com/experience/analytics/custom-dimensions/e-vars/e-var1".  Why is that not a nested structure?

**Metrics**

Metrics has properties such as "https://ns.adobe.com/xdm/data/metrics/direct-marketing/bounces" and "https://ns.adobe.com/xdm/data/metrics/commerce/checkouts".  Within this, what is the organization or domain of the namespace?  Do we need to organize both around "metrics" *and* around domains like "commerce"?  IMO we should either have just one "metrics" area for XDM, or have the metrics live in a domain-area specific namespace, but not both.  

How we do this probably depends on where we put the metrics.  If we put them under the domain (which is being proposed in #265) then having the domain in the namespace becomes highly redundant.

**Comment by kstreeter** [comment]
Hey @cdegroot-adobe, I feel like we can use structure to help with both of these cases.  

If "delivery" is an important organizing concept (which it appears to be, as there are several fields in the Campaign extensions with that namespace) then we could simply have a "delivery" sub-object, which in turn has all those fields, including the id (which could probably become an `@id`). 

Similarly, if we decide that metrics will tend to be embedded in the domain/area (as you noted as in #265) then we don't need to also include that domain/area in the namespace.  We could then keep just the '/xdm/metrics' space, or even drop that and call the field 'checkoutsMetric'.

In that last case, I would probably lean towards keeping the '/xdm/metrics' space, since we kind of expect to define lots of metrics.  But if that weren't true, I would probably lean the other way; we shouldn't create a new namespace just because appending 'Metrics' to a couple of fields is a little clumsy.

**Comment by trieloff** [comment]
Quick recap of the call I just had with @kstreeter 

- we should encourage everyone, especially the Campaign team to adhere to the principle of namespace conservation: create as few namespaces as possible, make namespaces as big as you can organizationally handle them (this should be reflected in `Contributing.md`)
- URIs are great for two things: they are concise pointers and they provide us (through DNS) with a global, conflict-free naming system. We should not parse or encourage parsing of URIs beyond that.
- Channels and Metrics are potentially unbounded domain spaces, but channels has a more reasonable approach to meta-categorization, as it has a `@type` attribute. Metrics don't which is encouraging URI parsing. A remedy would be to introduce `@type` for Metrics (Metric definitions), similar to Channels

**Comment by lrosenthol** [comment]
I have to take the complete opposite approach here.  Namespaces are *absolutely* a way to organize things as well as categorize them.  Especially in a environment like our own where there are *many* different orgs creating their own grammars.  We are already seeing this with everyone trying to put their stuff into xdm: - but their terms don’t match the same term used elsewhere.  We should have MORE not less…
In that vein, I am fine with URIs being the namespacing syntax - as it is defined to be - instead of simple terms.  Of course, that makes for less human-readable data (and larger), but it would be more correct

**Comment by kstreeter** [comment]
@lrosenthol, I don't anyone is proposing to take away URIs.  As you say, this is the method we use to allow different organizations to create their own grammars.  The inconsistency being pointed out is that we have cases that within a org-defined grammar, we have additional namespaces being used where JSON structure would suffice and would be more consistent with how most of the schemas are modeled.

Please take a look at the [Campaign extensions for ExperienceEvent](https://github.com/adobe/xdm/blob/master/extensions/adobe/experience/campaign/experienceevent.schema.json).  There are several constructs modeled there (Messages, Campaigns, Delivery attributes) that only exist *inside the namespace URIs*.  Understanding the organization of the extension requires mentally parsing the URIs to see how they are related.  This goes against the "opaqueness" property of the URI.

**Comment by kstreeter** [comment]
Hi @lrosenthol, did my last help with your concerns on this?  I'd like to start filing PRs for the specific issues identified, since we will need for the next milestone.

**Comment by lrosenthol** [comment]
Yes, I believe that we can move forward and look at specific examples...

**Comment by kstreeter** [comment]
Thanks @lrosenthol.  We already have a PR #302 that will cover some of this.  I am preparing PRs for the others.
