### ISSUE TITLE
Model JSON HAL (Hypertext Access Language)

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#28]
## What are the schemas that are affected by the issue

The directory schema in #96 depends on the `_link` property, which is following https://tools.ietf.org/html/draft-kelly-json-hal-08 - JSON HAL is not modeled at the moment.

## What are examples of products that are impacted by the issue

- Creative Cloud Files

**Comment by lucianfelix** [comment]
Hi,

I'm woking at the CICD api proposal and I need some guidance about how HAL applies to this.

How can we link to HAL schema definitions? Link an external one like [hyperschema.org](http://hyperschema.org/mediatypes/hal) or use our own (which would be proposed in a PR)?

Should the schemas also use _embedded part of HAL? There are schemas in the current model that use children as container for parent-child relations.

Are the links the only way of specifying relations or is it allowed to have redundant <rel_name>_id properties that point to liked object?

Thanks,
Lucian

**Comment by trieloff** [comment]
Hi @lucianfelix 

> How can we link to HAL schema definitions? Link an external one like hyperschema.org or use our own (which would be proposed in a PR)?

We should have our own, residing in `schemas/external/hal` with proper description and examples. You can use an external definition as a starting point, if the license permits and is compatible.

**Comment by trieloff** [comment]
> Should the schemas also use _embedded part of HAL? There are schemas in the current model that use children as container for parent-child relations.

Only model `_embedded` if you need it. As I see it right now, I would not replace all (or even most) of the nested documents we have in our current schemas with HAL `_embedded` relations.

**Comment by trieloff** [comment]
> Are the links the only way of specifying relations or is it allowed to have redundant <rel_name>_id properties that point to liked object?

We do already have examples where we are linking (or pseudo-linking) through `somethingID` properties. Most of this is in `assets` where we point to old `versionID`s. For new stuff, I'd uniformly use HAL, so that this style of linking can be expected in most places.

**Comment by trieloff** [comment]
This would also eliminate the need for the `reference` schema that got introduced with #59 and #60
