### ISSUE TITLE
Add primary optional boolean flag to /context/identity

### ISSUE THREAD

**Issue by cdegroot-adobe** [adobe/xdm#286]
## What are the schemas that are affected by the issue
Non breaking addition to:
`/xdm/context/identity.schema.json`

## What are examples of products that are impacted by the issue
Profile Service

Add a boolean field that allows an identity to be flagged as being the primary one to be used to partition or index the identity.

**Comment by lrosenthol** [comment]
Not sure how that works if you only have a single profile, @cdegroot-adobe .   This would only make sense in the context of an array of profiles...

**Comment by cdegroot-adobe** [comment]
The use case that the team have here is:
There is a scheduled update of a profile record coming from a system that is mastering some of the profile data that we are incorporating into the golden profile. Each scheduled date we receive an update to each profile that has new information (can be 150M profiles). Typically we keep all updates for all sources due to complex merge semantics. On request we merge the golden profile _at read time_ based on a set of merge rules. This is a high cost calculation. 
One optimization is that if profile updates are coming from the same system, and have the same "primary" identity we can do a _write time merge_ for that source. This is a significant cost reduction with no impact to the quality of the final golden profile.

**Comment by lrosenthol** [comment]
I can see that need in your very specific workflow, which is why it would be a great use case for an extension.

**Comment by kstreeter** [comment]
@lrosenthol, what @cdegroot-adobe is just a specific example.  A key aspect of the identity framework is that in general every end-user has multiple identities (because they are using multiple devices, etc).  When multiple identities are being managed, there will always be a need to organize them, and that organization will almost always mean picking one as the root or primary one.  The data merge example is just one case of that.

**Comment by lrosenthol** [comment]
That's how XC is using identifies and profiles, but it's not how other folks do/can/will use them.  We should not be imposing any specific business logic on the schemas - they are just data schemas.  How individual clients use them is not for us to say.

**Comment by cdegroot-adobe** [comment]
Done.
