### ISSUE TITLE
Change Campaign resource name to handle protobuf parsing

### ISSUE THREAD

**Issue by saurabhere** [adobe/xdm#301]
## What are the schemas that are affected by the issue
extensions/adobe/experience/campaign/experienceevent.schema.json

## What are examples of products that are impacted by the issue
Adobe Campaign

According to @cmathis  "One of the limitations of Protobuf is having one object/message named “campaign” contain another object named “campaign” as well. "
This is because the uri of the campaign resource becomes "https://ns.adobe.com/adobe/experience/campaign/campaign". 

This can be avoided by changing the name of the campaign resource from `campaign` to `marketingCampaign`.

**Comment by lrosenthol** [comment]
Or stop using Protobuf....
(I have no objections to the rename)
