### ISSUE TITLE
What information is encoded in the geocoordinates.@id field?

### ISSUE THREAD

**Issue by stormybriggs1** [adobe/xdm#308]
## What are the schemas that are affected by the issue
schemas/external/schema/geocoordinates.schema.json

## What are examples of products that are impacted by the issue
Adobe Analytics ingestion.

Working through the creation of an XDM object that included latitude and longitude I found that the placeContext.geo object requires an ID. That ID comes to us through the incorporation of geocoordinates. What is this ID meant to encode? Why is it required?

**Comment by lrosenthol** [comment]
There was a bunch of work done as part of the original Core Asset Data Model around handling of lat/long (and the like) for geospatial - but I can't seem to find the results here.  @dgeorge do you know where that ended up?

**Comment by dgeorge** [comment]
Here is what had previously been specified:

exif:GPSAltitude
- type: Float	
- description: GPS tag 6, 0x06. Indicates altitude in meters.

exif:GPSAltitudeRef
- type: Integer
- description: GPS tag 5, 0x5. Indicates whether the altitude is above or below sea level:
- 0 = Above sea level
- 1 = Below sea level
	 	 
exif:GPSLatitude
- type: GPS Coordinate (?)
- description: GPS tag 2, 0x02 (position) and 1, 0x01 (North/South). Indicates latitude.

exif:GPSLongitude
- type: GPS Coordinate
- description: GPS tag 4, 0x04 (position) and 3, 0x03 (East/West). Indicates longitude.

**Comment by stormybriggs1** [comment]
I am very happy that there is a place for latitude and longitude within XDM. I am confused about what should go in the ID field and why it is required. Could you please tell me more about this ID field? Thanks.

**Comment by cdegroot-adobe** [comment]
The @id is a mistake I believe:
https://github.com/adobe/xdm/blob/master/schemas/external/schema/geocoordinates.schema.json

I cannot see `@id in the schema.org schema and I do not believe it should be required.

I will put a PR in now to remove the required part.
