### ISSUE TITLE
Extend Analytics to include operating system ID and browser ID

### ISSUE THREAD

**Issue by stormybriggs1** [adobe/xdm#309]
## What are the schemas that are affected by the issue
extensions/adobe/experience/analytics/experienceevent.schema.json

## What are examples of products that are impacted by the issue
Adobe Analytics ingestion and all down stream consumers.

**Comment by lrosenthol** [comment]
This information is included in browserDetails referenced from https://github.com/adobe/xdm/blob/9783604737f91692a9529d9e3a0b9d9bb6411b9d/docs/reference/context/environment.schema.json (among other places)

**Comment by cdegroot-adobe** [comment]
@lrosenthol The IDs by which different systems know that browser or OS by is not part of the current schemas. Different systems have different IDs. Device Atlas etc. In this case the issue is outlining something in the scope of Analytics as it is in the Analytics extension.

Make sense?
