### ISSUE TITLE
How to distinguish Abstract from Concrete schemas

### ISSUE THREAD

**Issue by cdegroot-adobe** [adobe/xdm#330]
The following note defines that there are Abstract and Concrete schemas and the difference.
"https://ns.adobe.com/experience/implementations"

How do we indicate in a schema file that it is Abstract or not?

Thanks C.

**Comment by trieloff** [comment]
The basics are described here: https://github.com/adobe/xdm/blob/master/docs/abstract.md

An abstract schema has a `definitions` object, (i.e. it is extensible, and can be used in other schemas) but it does not reference any `definitions` or define `properties` on its own.

**Comment by cdegroot-adobe** [comment]
@trieloff - thx.
