### ISSUE TITLE
Guidance needed on how to implement "open" enums, e.g examples.

### ISSUE THREAD

**Issue by cdegroot-adobe** [adobe/xdm#334]
@trieloff @kstreeter @lrosenthol 

There are a number of questions regarding the best way to implement open `enums`

Suggestions are to use the `example` syntax to allow users of the schema the best chance of selecting a common value in cases where we cannot fully constrain the values in an enum. How do we maintain a value and description in these cases for example?

Can one of the editors provide an example of how best to implement this please.

**Comment by cdegroot-adobe** [comment]
@kstreeter described the following pattern:
The places that have “meta:enum” and no enum are open/extensible enums: places where we know some of the valid values, but the list is not necessarily exclusive. 

Example: Regular closed enum
```
        "xdm:gender": {
          "title": "Gender",
          "type": "string",
          "enum": ["male", "female", "not_specified", "non_specific"],
          "meta:enum": {
            "male": "Male",
            "female": "Female",
            "not_specified": "Not Specified",
            "non_specific": "Nonspecific"
          }
```

Example Open "Enum" e.g recommended examples.
```
        "xdm:type": {
          "title": "Type",
          "type": "string",
          "description": "Type of device being tracked.",
          "meta:enum": {
            "mobile": "Mobile",
            "tablet": "Tablet",
            "desktop": "Desktop",
            "ereader": "E-Reader",
            "gaming": "Gaming Console",
            "television": "Television",
            "settop": "Set-top Box",
            "mediaplayer": "Media Player"
          }
        }
```

**Comment by trieloff** [comment]
That's correct. `meta:enum` is purely for documenting known values. For a hard `enum` all values are known and can be documented, for a soft enum (really just a string) only some values can be documented.

**Comment by lrosenthol** [comment]
I think we need a way for folks to know what are open and what are closed enumerations - ala XMP choices.

**Comment by trieloff** [comment]
@lrosenthol 2793ca0 provides more detail. I think this fixes it. If you have a suggestion how to address this in the generated documentation, please raise an issue with jsonschema2md
