### ISSUE TITLE
Use dc:title instead of xdm:title

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#34]
We currently have our own xdm:title, which is semantically equivalent with schema.org#title, so we should use that instead

## What are the schemas that are affected by the issue

Page

## What are examples of products that are impacted by the issue

- AEM

**Comment by trieloff** [comment]
Paging @tripodsan

**Comment by lrosenthol** [comment]
@trieloff How does this relate to dc:title, which we also have from DublinCore and XMP?

**Comment by trieloff** [comment]
`dc:title` is probably an even better choice.

**Comment by lrosenthol** [comment]
Agreed - thanks!
