### ISSUE TITLE
Add search/searchEngineID and search/searchEngineIDService

### ISSUE THREAD

**Issue by stormybriggs1** [adobe/xdm#347]
## What are the schemas that are affected by the issue
schemas/context/search.schema.json

## What are examples of products that are impacted by the issue
Analytics ingest and downstream.

## Description
Some solutions may encode the search engine field as an identifier that would relate to some known look up service. This would allow one the freedom to fill in an ID and related look up service as opposed to always filling in a friendly name for a search engine.

**Comment by cdegroot-adobe** [comment]
@kstreeter please put this in the June 15th Milestone.

**Comment by lrosenthol** [comment]
What good is an ID if you can't match it up to known values.  Also, that schema needs to be fixed as keywords is not the correct value - it should be query.

**Comment by trieloff** [comment]
+1 on @lrosenthol's comment: make the search engine ID a `uri`, and the problem of looking things up has been solved.

Please also see #99 – the plain text string without any semantic or classification is clearly not useful
