### ISSUE TITLE
Profile and ExperienceEvent schema doesn't show any required field

### ISSUE THREAD

**Issue by rkpandey** [adobe/xdm#352]
## Unified Profile Service and other services of ACP
The properties tables of ExperienceEvent and Profile don't show any field as required field. In earlier version of schema, timestamp and endUserIDs in ExperienceEvent and identities in Profile were required fields.

**Comment by cdegroot-adobe** [comment]
@kstreeter  please put this in the June 15th Milestone. It is causing confusion.

**Comment by cdegroot-adobe** [comment]
Closing this as #349 is a more complete.
