### ISSUE TITLE
Video Analytics additions for ExperienceEvent

### ISSUE THREAD

**Issue by cdegroot-adobe** [adobe/xdm#364]
## What are the schemas that are affected by the issue
`/context/experienceevent.schema.json`

## What are examples of products that are impacted by the issue
Video Analytics
Video Ads
Media marketing in Target

**Comment by cdegroot-adobe** [comment]
@kstreeter the team has been working on this for a while, but it is only now getting ready for wider review. It is a simple set of schema additions, but has a lot of properties. It is quite large in that regard. We will need to give it special attention. Analytics needs this for the first data onboarding. Please consider it for June 15th.

**Comment by lrosenthol** [comment]
When do you expect to have a PR for this @cdegroot-adobe ?

**Comment by kstreeter** [comment]
@cdegroot-adobe we can't really schedule this until the PR is available.

**Comment by fmeschbe** [comment]
With PR #417 merged, this issue can be closed. Follow-up work tracked by issue #435 and PR #433
