### ISSUE TITLE
Add new endUserIds in experienceEvents

### ISSUE THREAD

**Issue by saurabhere** [adobe/xdm#369]
## What are the schemas that are affected by the issue
experienceEvent
## What are examples of products that are impacted by the issue
Campaign

The current experienceEvent schema allows for 4 types fo enduserIds(identities).
In Campaign, there are cases when the recipient is not known as a record in the database, but their information comes through a payload. The only identifier in this case is their email.
Similar case is for SMS where phone number is the identifier.
There is a need to add at least these 2 new endUserIds in the experienceEvent schema to support this.

Mention: @cdegroot-adobe

**Comment by trieloff** [comment]
Sounds reasonable.

**Comment by cdegroot-adobe** [comment]
@kstreeter - This needs to be in the June 15th milestone. Internally we already have standard namespaces defined for the two requested endUserIds.

**Comment by kstreeter** [comment]
@cdegroot-adobe, when can we expect the PR?

**Comment by cdegroot-adobe** [comment]
@kstreeter - in now as #381
