### ISSUE TITLE
Change ID format from "uri" to "uri-reference"

### ISSUE THREAD

**Issue by kstreeter** [adobe/xdm#418]
As we have continued to build tooling around XDM, we have encountered some variation in how strict tools are about validating or generating code for properties with a format of "uri".  Some tools allow for both relative URI references as well as absolute ones, while others only accept complete URIs in absolute form.

It appears this variation stems from changes made between JSON Schema draft 4 and draft 6.  In draft 4, the specification was not clear about whether format "uri" was intended to be absolute or not.  Tools went different direction on this, and the issue was addressed in draft 6.  Unfortunately, they chose a method that was not really backwards compatible, designating format "uri" as strictly an absolute URI, and adding a "uri-reference" to encompass the more expansive form.

A particular place where we use format "uri" is for describing the JSON-LD construct `@id`.  In JSON-LD, `@id` is allowed to be a relative reference.  So our use of format "uri" (under draft 6, which we have adopted in XDM) has overly constrained that definition.

We have a number of tools and components that assume it is acceptable to use the relative URI form in `@id` fields, based on the JSON-LD definition.  We are encountering issues in some toolchains that fully honor the definition of format "uri", and reject data that uses the relative form.

Since our use of `@id` is intended to align with its definition in JSON-LD, I would like to propose that we fix our mapping for `@id` to use format "uri-reference" rather than format "uri".  This will fix the tool chain issues, and bring us closer in sync with JSON-LD.

## What are the schemas that are affected by the issue

All

## What are examples of products that are impacted by the issue

All

**Comment by kstreeter** [comment]
@lrosenthol @chrisdegroot @ogoldman please let me know what you think of this proposal.  

This should not be a breaking change from a schema perspective (we are relaxing constraints), but it will impact tooling that generates code (POJOs, etc) from schema definitions.  If we adopt this, I suggest we migrate definitions on a case-by-case basis after considering impact.

**Comment by cdegroot-adobe** [comment]
I agree that the JSON-LD specification is going in a direction that forces us to make this sort of decision.

My concern is that there are three states, and there are only two options, and neither of them are what we want.

`uri-reference` -> spec says stuff about it being local to document base 
`uri-absolute` -> what json-ld really seems to say it wanted to go to, but alas did not.
`uri` -> should conform to `uri-reference` OR `uri-absolute`

Is short I think unless we are ok saying a `uri-reference` can be a absolute or relative uri we may not have a clear option.

**Comment by cdegroot-adobe** [comment]
Actually, after reading the URI spec a bit more I get that `uri-reference` is either an absolute of reference.

Approve for sure.

**Comment by cdegroot-adobe** [comment]
@lrosenthol - can you approve this and move forward with a PR?

**Comment by lrosenthol** [comment]
I agree - this looks good to me.   

So do we need to then make this change in *every* schema, @cdegroot-adobe ?

**Comment by cdegroot-adobe** [comment]
@lrosenthol - I would prefer we do it everywhere. @jwen-adobe can you look at how to do this please? I will be away for several weeks so I do not have the cycles.

**Comment by jwen-adobe** [comment]
@cdegroot-adobe Please share a example here about the changes to be made. Also when u say everywhere, that means include those non-experience platform xdm schemas as well like assets etc.?

**Comment by jwen-adobe** [comment]
@kstreeter Some @id field does not have format associated, do u want to add a format for that case as well? And this change is for all the schemas which includes non experience related?

**Comment by jwen-adobe** [comment]
unless otherwise, I will create a script to change those schemas contain @id with format "uri" and change their format to "ur-reference"

**Comment by lrosenthol** [comment]
Looking good here...
