### ISSUE TITLE
Extend XDM ExperienceEvent with Target Activity Specific Data

### ISSUE THREAD

**Issue by vazdauta** [adobe/xdm#457]
Target Alpha Connector implementation contains details related to request, the big part of them belongs to common XDM schema ( like: deviceAtlas, browser details, geo details, order information etc. Target specific data are mbox name, client code, tntId. 
In order to be able to build reporting and use it for machine-learning should be more data about activities execution and events generated by them.

During this phase we are going to add more details regarding the activities (campaigns) execution during an mbox call.

**Comment by vazdauta** [comment]
Fixed in #456

**Comment by lrosenthol** [comment]
Confirmed resolved and PR merged.
