### ISSUE TITLE
Add Orchestration context in Campaign Experience Event

### ISSUE THREAD

**Issue by ksradobe** [adobe/xdm#465]
## What are the schemas that are affected by the issue
1) extensions/adobe/experience/campaign/experienceevent
2) extensions/adobe/experience/campaign/orchestration/reportingevent

## What are examples of products that are impacted by the issue
Voyager
Campaign

"reportingevent" schema is having all the attributes which constitute a valid reporting event. Here certain attributes can be pulled out from reporting event and make them available to other experience event. (Ex: Here, "Orchestration Context" in Campaign experience event). This will increase the consumability of common orchestration properties. 

Another change is to add "Delivery name" and "Campaign Name" which is kind of friendly identifier for the user to remember instead of simple integer id. Similarly "Delivery Label" is a descriptive name given to the marketing activity for making it easily searchable.

**Comment by lrosenthol** [comment]
@ksradobe Will you be submitting PRs for these issues??

**Comment by ksradobe** [comment]
I created #464 as well and added my contribution there. As I particularly didn't created an issue for 464, I created this new one in Issues category.
If it is acceptable to take #464 then we can close this.

**Comment by lrosenthol** [comment]
Yes, I'll close this and well work with #464.  thanks!
