### ISSUE TITLE
Make experience schemas xed convertable for 0.9.9.4 release

### ISSUE THREAD

**Issue by jwen-adobe** [adobe/xdm#473]
## What are the schemas that are affected by the issue
Schemas under xdm/extensions/adobe/experience/target/

## What are examples of products that are impacted by the issue
platform xdm tooling, platform xdm schemas

**Comment by lrosenthol** [comment]
Would be much better if the Platform itself support XDM natively and we could dump XED...

**Comment by jwen-adobe** [comment]
@lrosenthol I will let @kstreeter answer this, as currently our registry only can take xed format. It will be our long term goal I would think.
