### ISSUE TITLE
Define Logical Data Types for XDM

### ISSUE THREAD

**Issue by kstreeter** [adobe/xdm#493]
While the JSON Schema descriptions we use to describe models contain a fairly complete model for data types as used in JSON, they don't completely describe how these JSON types would map to corresponding types in non-JSON representations of a model.  

As the XDM descriptions are used across many different representations (Java classes, Parquet files, Spark SQL Dataframes, just to name a few), we need to make sure that the logical meaning of the types we use is defined.

## What are the schemas that are affected by the issue
All

## What are examples of products that are impacted by the issue
All

**Comment by lrosenthol** [comment]
Didn't we discuss this as being handled by JSON schema and using its support for arbitrary types, such as those in XML Schema?

**Comment by kstreeter** [comment]
Hey @lrosenthol, take a look at PR #495 and see if the doc makes it clearer what we'd like to do with this.  Types are definitely defined in terms of JSON Schema, but we do need to describe what the set of possible logical types are, since each one has to mapped to it corresponding construct in each technology that we use with XDM.
