### ISSUE TITLE
businessReason name change

### ISSUE THREAD

**Issue by mickaelbentz** [adobe/xdm#496]
Change the label of an XDM field from businessReason to EventID
The field to modify is situated here:
https://www.dropbox.com/s/gmpfguddiqdeseh/Screenshot%202018-08-28%2018.10.40.png?dl=0

**Comment by reivaxy** [comment]
@mickaelbentz shouldn't it be "eventID" ? it would look more in line with xdm field naming

**Comment by reivaxy** [comment]
This issue can be closed, not sure who can close it. @mickaelbentz ? @cfraser ?
Thanks

**Comment by mickaelbentz** [comment]
Done on Jira. Should I do something else ?
