### ISSUE TITLE
Schema filename unification needed

### ISSUE THREAD

**Issue by dmitry-shkolnik** [adobe/xdm#51]
While most of the complex names are in kebab-case (e.g. `schemas/assets/copyright-owner.schema.json`), some are still in concatenated lowercase. Files need to be renamed, `$id` property changed respectively and `$ref` in other files  updated.

## What are the schemas that are affected by the issue
```
schemas/common/eventenvelope.schema.json
schemas/common/identityprovider.schema.json
schemas/context/personname.schema.json

schemas/context/person.schema.json
  18:  "$ref": "https://ns.adobe.com/xdm/context/personname",

schemas/common/principal.schema.json
  16: "$ref": "https://ns.adobe.com/xdm/common/identityprovider#/definitions/xdm:name"
```

**Comment by trieloff** [comment]
Agree on Identity Provider and Person Name. `EventEnvelope` is (to a degree) a made-up word anyway, so I'd leave it as is.
