### ISSUE TITLE
Identity Provider/Principal needs clean-up

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#52]
While working on #51 I noticed some inconsistencies in the `principal` schema. It references the `xdm:name` property from Identity Provider, implying that it is the identity provider's name. In reality, it looks like it is the principal's name, which is confusing.

Principal should have a property `xdm:provider` which points to the Identity Provider.

## What are the schemas that are affected by the issue

- Principal
- Identity Provider

## What are examples of products that are impacted by the issue

- all

**Comment by trieloff** [comment]
Additional suggestions:

- [ ] use `@id` instead of `xdm:name`
- [ ] make it a `uri`
- [ ] make `xdm:provider` a `uri`, too.

Feedback from @theManikJindal and @fmeschbe welcome.

**Comment by theManikJindal** [comment]
> In reality, it looks like it is the principal's name, which is confusing.

I do not know if it is just me, but from the [principal example](https://github.com/adobe/xdm/blob/master/schemas/common/principal.example.1.json), I am failing to see the confusion.

Also, my original motivation for not using `@id` was that it is hard to assign **URIs** to identity providers. But if we can find a way to do that, then let's.

**Comment by trieloff** [comment]
Making up a URI is not too hard. Trying to figure out what a random string that is pointing to another entity means and where to go for the entity is much harder.

I'll take a stab at this.
