### ISSUE TITLE
Image Schema not derived from Asset Schema

### ISSUE THREAD

**Issue by mburbidgadobe** [adobe/xdm#56]
Should the image schema be derived from the asset schema? Maybe I missed it , but it does not look like it references the asset schema.

**Comment by trieloff** [comment]
Yes, it should be derived from `asset`. Let me check.

**Comment by trieloff** [comment]
And it is derived from `asset`, it's just not yet declaring `meta:extends`.

**Comment by trieloff** [comment]
Now that #15 has been merged, we can update all schemas to have the correct `meta:extends` keyword
