### ISSUE TITLE
xdm:createDate & xdm:modifyDate required?

### ISSUE THREAD

**Issue by mburbidgadobe** [adobe/xdm#57]
In the asset schemas, `xmp:createDate` and `xmp:modifyDate` are required. How can these be required? Where would the value come from if the asset has now xmp packet?

**Comment by trieloff** [comment]
@mburbidgadobe I read your comment as:
> where would the value come from if the asset has *no* xmp packet?

**Comment by trieloff** [comment]
I agree, they should not be required.
