### ISSUE TITLE
Rendition retrieval needs to support params on GET

### ISSUE THREAD

**Issue by lrosenthol** [adobe/xdm#58]
From another doc
>A _rendition_ resource may be retrievable, although user agents cannot specify the desired size. This permits user agents to fetch a rendition in a single request, when a rendition is available for the given asset and only at some default size determine by the server. User agents that wish to obtain renditions at a particular size should first use a HEAD (or other) request to obtain a full set of rendition links.

>This seems to imply that a client can't pass any parameters to the GET on a rendition - that is extremely problematic for custom renditions

**Comment by trieloff** [comment]
@lrosenthol this seems to be Content Services related, not XDM-related. Please re-open if this is indeed an XDM issue.
