### ISSUE TITLE
Exclude Escape Characters from Property Names

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#61]
## What are the schemas that are affected by the issue

all

## What are examples of products that are impacted by the issue

all products that need to escape certain characters in property names.

**Comment by cdegroot-adobe** [comment]
@trieloff do you have some examples of cases where this is an issue? Is it only from other preexisting specifications that we want to incorporate?

**Comment by cdegroot-adobe** [comment]
@trieloff - is this still a valid concern. If so please provide more details, if not please close.
