### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by adipan** [adobe/xdm#636]
## What are the schemas that are affected by the issue
Please refer -
https://github.com/adobe/xdm/blob/master/CONTRIBUTING.md#writing-styleguides
There is a line 

> For all writing, please follow the Adobe I/O style guide.

The link in above line does not work anymore, and points to https://www.adobe.io/about/contributing/doc-style_master.html

**Comment by Soundug** [comment]
@adipan How do you want it to be fixed? Can you elaborate. I would like to contribute
