### ISSUE TITLE
Clean up Address and Geo

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#64]
Looking at the `experience-cloud-staging` branch and have a couple of suggestions for Address and Geo that go beyond cosmetics.

Address is now extending Geo, this allows us to reduce a lot of redundant info.

* Is there a good reason for cutting off the country part of `stateProvinceISO`? Keeping it would make it easier to describe the data (just ISO 3166-2) and it's unlikely that someone wants to look at region independently from country.
* Are there objections against moving `stateProvinceISO` up to Geo, replacing the current (free-form) stateProvince?

**Comment by trieloff** [comment]
@kstreeter @jwen-adobe

**Comment by jwen-adobe** [comment]
@cmathis @cdegroot

**Comment by kstreeter** [comment]
I agree, it would be good to use a standard definition such as ISO 3166.  And I also agree we could move the region up to geo.

**Comment by cfraser** [comment]
@kstreeter @trieloff Could we just stick with the name `stateProvince` and document that it follows ISO3166?

**Comment by trieloff** [comment]
@kstreeter @cfraser – agree on both counts: let's use a standard definition for values like this, and make the standardized (ISO) name the default, i.e. shorter property.

**Comment by trieloff** [comment]
Merging 028b2c4 depends on #63
