### ISSUE TITLE
What's the deal with List Details?

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#65]
In `experience-cloud-staging`.

It looks like an orphaned schema that is not being used anywhere.

@jwen-adobe @kstreeter?

**Comment by jwen-adobe** [comment]
@trieloff This schema is actually used by Analytic extension which is not part of this PR.

**Comment by trieloff** [comment]
Thanks, then I will remove it from the staging branch.

**Comment by jwen-adobe** [comment]
Removed from staging. Will add back along with analytic extension then.

**Comment by trieloff** [comment]
Fixed in 16e1892
