### ISSUE TITLE
Questions on Organizations (Experience Cloud)

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#66]
Right now, we have following external IDs in this schema:

- `duns`: Dun & Bradstreet
- `sicCode`: [SIC Code](https://en.wikipedia.org/wiki/Standard_Industrial_Classification)

Given that neither is the only provider of organizational identification or classification (in particular SIC, which is being replaced with NAICS since **1997**), we could model it in a more extensible way:

```json
  "xdm:identifiers": [
    {
      "@type": "http://dnb.com",
      "xdm:id": "1262"
    }
  ],
  "xdm:classifiers": [
    {
      "@type": "http://www.companieshouse.gov.uk/infoAndGuide/sic/sic2007.shtml",
      "xdm:class": "1241"
    }
  ]
```

That way, new classifiers and identifiers can be added easily, while we only have to deal with a couple of known `@type` values.

**Comment by trieloff** [comment]
@kstreeter @jwen-adobe

**Comment by kstreeter** [comment]
I'm not sure I see the advantage of making these arrays.  We have actually had this conversation in several contexts.  In general, no processor is going to iterate over an array.  They will look for the specific field they care about, if it is present.  This is better represented as a specific field, just as it is now.  You extend it by adding new fields.

Note that we should not use fields with an @ in models that are intended to be stored in the data platform.  It will complicate our "data safe" encoding.

**Comment by trieloff** [comment]
@kstreeter good point on the "accessibility" of arrays. It's indeed a bit cumbersome. Thinking about this a bit more, it might be a good scenario for our extensions. Because the D&N reference is essentially a vendor extension, I think it should live on the same level as references to other company databases like [Orbis](https://www.bvdinfo.com/en-us/our-products/company-information/international-products/orbis), [Datafox](http://www.datafox.com), [Angellist](https://angel.co), or [Crunchbase](https://www.crunchbase.com) (these are just the ones I have used in the past).

It would look like this:

```json
"xdm:identifiers": {
  "http://dnb.com": "1262",
  "https://angel.co/": "https://angel.co/omniture"
}
```

Accessing the D&B number would be as simple as `data.xdm:identifiers.['http://dnb.com']`, i.e. not much more difficult than `data.xdm:dnbCode`.

**Comment by kstreeter** [comment]
Yes I think this is the right direction.  It's just a property, and qualified like other properties are: with a prefix or as a full IRI.

We may need to think a little about whether us defining something like "http://dnb.com" as part of XDM is right though.  Definitely if D&N or some other vendor defines the field for themselves, it would be given a namespace with an authority they control.  

But if we choose to include in XDM, we really need to include it under a reserved XDM prefix.  I don't think that is unreasonable: de facto standards are still standards, and as long as we can describe the use of the field completely it would be okay for us to include in the core standard.

I'm not really knowledgable on the prevalence of using the D&N number versus some of the other vendors you mentioned, so I'm not really able to make a claim as to whether it is really a de facto standard or not.  I'm interested in @cdegroot 's take on that.

**Comment by trieloff** [comment]
I'd also add, if we feel confident enough to make D&B a core property, we should talk to them to get their OK and preferred namespace URL. Otherwise, I agree, let's use an Adobe prefix for the vendor namespace URL.
