### ISSUE TITLE
Cleaning up Place/Physical Location

### ISSUE THREAD

**Issue by trieloff** [adobe/xdm#67]
In `experience-cloud-staging`, the physicallocation schema describes what normal people would call a place. I'd suggest renaming it to `context/place`.

In addition, we should model the `containsLocations` using #28 (HAL), so that we can get rid of the `reference` schema.

**Comment by cfraser** [comment]
I like Place. It also aligns nicely with the Schema.org as well.

**Comment by kstreeter** [comment]
I am okay with calling this "Place".  An I agree that we should get rid of reference.  I'm not sure how HAL would work here though, or why we need it.  If the ID of a place is a URI, shouldn't containsLocation just be a URI, too?  We should not assume that these IDs represent network accessible resources, which is what HAL would imply.

**Comment by trieloff** [comment]
We are using HAL in other parts of the platform, so it makes sense to express links between schemas in a common way. It gives us real JSON as Hypermedia and (something that I like about it) an equivalent to `rel=` expressions.

**Comment by trieloff** [comment]
We now have #70 and can easily use HAL.

**Comment by kstreeter** [comment]
@trieloff, I feel like this is an area where how the schema is primarily used really has an effect on the best way to model relationships.  

I definitely understand how a schema that is primarily used as part of a REST API would benefit from modeling relationships using HAL or something like it.  You can assume these systems are operating on instances of data that have direct, addressable links to each other.  

But schemas that will be stored in support of big data workflows will not work like this.  Instances of these schemas are usually not accessible directly, but only indirectly via a data warehousing mechanism which processes and filters the data.  The data warehouse may have multiple layers of metadata that describe relationships across available datasets in multiple ways, depending on the business process being supported.  These relationships may change over time, while stored data is something that (for all intents and purposes) lives forever.

For data systems, it is better to model relationships using opaque keys, which can be linked together based on metadata at the dataset level.  This metadata can be configured by a analyst or data engineer that understands that data, or can be extracted from the data itself by introspecting the data.

**Comment by trieloff** [comment]
The two alternatives as they stand looks like this:

## Status Quo
```json
{
  "@id": "https://data.adobe.io/entities/places/locationid-123456",
  "xdm:address": {
    "@id": "https://ns.adobe.com/entities/address/123",
    "xdm:primary": false,
    "xdm:street1": "345 Park Ave",
    "xdm:city": "San Jose",
    "xdm:stateProvince": "California",
    "xdm:stateProvinceISO": "CA",
    "xdm:postalCode": "95110",
    "xdm:country": "United States",
    "xdm:countryCode": "US",
    "schema:latitude": 37.3382,
    "schema:longitude": 121.8863,
    "xdm:status": "active",
    "xdm:lastVerifiedDate": "2018-01-02"
  },
  "xdm:phoneNumber": "1-408-888-0000"
  "xdm:containsLocations": [
    {
      "xdm:ref": "123457",
      "xdm:type": "PhysicalLocation"
    },
    {
      "xdm:ref": "123458",
      "xdm:type": "PhysicalLocation"
    }
  ],
  "xdm:containedByLocation": "https://data.adobe.io/entities/places/locationid-123454"
}
```

## Proposed (HAL)
```json
{
  "@id": "https://data.adobe.io/entities/places/locationid-123456",
  "_links": {
    "contained-in-place": { "href": "https://data.adobe.io/entities/places/locationid-123454" },
    "contains-place": [
      { "href": "https://data.adobe.io/entities/places/locationid-123457" },
      { "href": "https://data.adobe.io/entities/places/locationid-123458" }
    ]
  }
  "xdm:address": {
    "@id": "https://ns.adobe.com/entities/address/123",
    "xdm:primary": false,
    "xdm:street1": "345 Park Ave",
    "xdm:city": "San Jose",
    "xdm:stateProvince": "California",
    "xdm:stateProvinceISO": "CA",
    "xdm:postalCode": "95110",
    "xdm:country": "United States",
    "xdm:countryCode": "US",
    "schema:latitude": 37.3382,
    "schema:longitude": 121.8863,
    "xdm:status": "active",
    "xdm:lastVerifiedDate": "2018-01-02"
  },
  "xdm:phoneNumber": "1-408-888-0000"
}
```

I can see a number of different persistence options that would apply to this place schema including:

- analytical, columnar database
- analytical graph database
- relational database
- document database

But most importantly, the level of indirection in both variants is the same:

* getting the first child place with `relation`: `data.xdm:containsLocations[0].xdm:ref`
* getting the first child place with HAL: `data._links.contains-place[0].href`

In my mind, there are two ways to go from here:

1. drop the `relations` bit entirely, and make `xdm:containsLocations ` a plain array of URIs
2. use one way of linking consistently across XDM, which, as prescribed by ACP, is HAL

I don't want to make up complex new rules for linking that are used in only once place. So let's either link simply, or complex, but consistently.

**Comment by trieloff** [comment]
Another note: http://schema.org/Place has some property names that we should adopt instead of our own.

**Comment by cfraser** [comment]
@trieloff which property names did you have in mind?

**Comment by trieloff** [comment]
containedInPlace/containsPlace are the ones that I stumbled over, let's just have a look if there are more.

**Comment by kstreeter** [comment]
@trieloff, it may not have been clear but in my first comment I was suggesting what you describe in (1): get rid of the reference, and just use URIs.  This is compatible with the definition we have for @id, which is a URI.  These URIs may or may not be accessible network locations that would work with a HAL type system.

**Comment by trieloff** [comment]
Sounds good, I like the simplicity.
