### ISSUE TITLE
Add an Optional Correlation ID to Experience Event

### ISSUE THREAD

**Issue by adobe-activation** [adobe/xdm#689]
## What are the schemas that are affected by the issue
https://github.com/adobe/xdm/blob/master/schemas/context/experienceevent.schema.json

## What are examples of products that are impacted by the issue
Target, Analytics, ECID, Ad Cloud, Platform

**Summary**
The larger Experience Edge Project has a couple work streams which include Unified JavaScript and Unified Data Collection on a common Domain.  ( For details of that project see: https://wiki.corp.adobe.com/display/DMSArchitecture/Experience+Edge ) As this new unified JS library is sending data to Adobe rather than it's acquired solutions, it has an opportunity to fix a long standing issue of not being able to tie events (such as hits or page views) together into a single grouping.  For example in SPAs and mobile the concept of page loads or page views are fluid and there may not be a single point in time page load in the traditional sence. Another example is the A4T case where we do crazy gymanstics both client side and server side to tie a Personalization view to an Analytics Page View.  This this partcilar case the JS library is likely to send mutiple commuincations and mutiple events and yet the reporting is likley to want to group these together.  Ex: Top of page an ECID is requested and and authenticated state of the user is recorded, subsequently as personalization request for content is made, lastly a page view or page bottom call is made to record the visit and record which personalized experience or activity was visible.  Likely 3 commuincations or beacons were sent and yet there may be a desire to "stitch" these or group them together.   THis is just one of many examples. 

To address these and other use cases, we are proposing an optional grouping or Correlation ID be added to the Experience Event that consumers of the ID can use to stitch or group events together both with Adobe and Non-Adobe products whenever two or more events should be correlated together. 

**For more Details see:** https://wiki.corp.adobe.com/display/Activation/Universal+Event+Correlation

**Comment by littlebutty** [comment]
After receiving alpha customer feedback, we have decided to rename this field to something less confusing and more specific.  "Stitch ID" primarily to drive users toward it's original purpose of stitching hits together similar to the A4T type use cases and less about session or attribution type use cases.
